In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])#create one dimensional array

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.ndim)

1


In [7]:
b = np.arange(15) #arange = generate an 1-d array from 0 to 14
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
c = np.arange(12).reshape(2, 6) # generate array and change dimensions(6,2)OR(4,3)OR(3,4)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
print("type: ",type(c))  #Specify type of array
print("Dimension: ",c.ndim)#dimension of Array c
print("Shape",c.shape)#shape of (row,column) of array c
print("Length",len(c))#length of array c

type:  <class 'numpy.ndarray'>
Dimension:  2
Shape (2, 6)
Length 2


In [10]:

lp = np.linspace(0,10,5)  #create 4 equally spaced points 0-10 range inclusively
print(lp)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
lp2 = np.linspace(0,10,5, endpoint=False) # remove endpoint and other equally spaced values.
print(lp2)

[0. 2. 4. 6. 8.]


In [12]:
np.random.randint(55,100,6)  #create array of 6 random values in 55-100 range.

array([93, 65, 83, 85, 64, 58])

In [13]:
np.random.randint(55,100,6).reshape(3,2) #reshape the array according to row and column vectors.

array([[99, 83],
       [66, 64],
       [67, 88]])

In [14]:
np.random.rand(4)    #create an array of uniform distribution (0,1)

array([0.32082454, 0.37539024, 0.6930848 , 0.85790189])

In [15]:
np.eye(3)            #create a 3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.zeros(3)          #create array([0,0,0])

array([0., 0., 0.])

In [17]:
np.zeros((5,5))      #create a 5*5 2-d array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.random.randn(2,2) #return standard normal distribution vcenter around zreo.

array([[ 1.01210031, -0.06674096],
       [-0.43367667,  0.0690875 ]])

In [19]:
np.empty((2,3))      # uninitialized

array([[4.6408578e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [20]:
np.arange(0, 2, 0.3) # from 0 to a number less than 2 with 0.3 intervals

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [21]:
d3=np.ones((2,3,4), dtype=np.int16)       # all element are 1

In [22]:
print(d3)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [23]:
d3.shape

(2, 3, 4)

In [24]:
np.array([[1,2],[3,4]], dtype=complex) # complex array

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [25]:
np.array([(1.5,2,3),(4,5,6)])          # two-dimensional array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
np.array([2,3,4])                      # one-dimensional array

array([2, 3, 4])

In [28]:
A = np.array([[1,1],[0,1]])
print(A)
B = np.array([[2,0],[3,4]])
print(B)
A+B              #addition of two array

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


array([[3, 1],
       [3, 5]])

In [29]:
np.add(A,B)      #addition of two array

array([[3, 1],
       [3, 5]])

In [30]:
A * B            # elementwise product

array([[2, 0],
       [0, 4]])

In [31]:
A @ B            # matrix product

array([[5, 4],
       [3, 4]])

In [32]:
A.dot(B)         # another matrix product

array([[5, 4],
       [3, 4]])

In [33]:
B.T              #Transpose of B array

array([[2, 3],
       [0, 4]])

In [34]:
A.flatten()      #form 1-d array

array([1, 1, 0, 1])

In [35]:
B.flatten()      #from 1-d array

array([2, 0, 3, 4])

In [36]:
B < 3            #Boolean of Matrix B. True for elements less than 3

array([[ True,  True],
       [False, False]])

In [37]:
A.sum()          # sum of all elements of A

3

In [38]:
B.sum()

9

In [40]:
print(A)

[[1 1]
 [0 1]]


In [39]:
A.sum(axis=0)    # sum of each column

array([1, 2])

In [41]:
A.sum(axis=1) # Sum of each Row

array([2, 1])

In [42]:
A.cumsum(axis=1) # cumulative sum along each row

array([[1, 2],
       [0, 1]])

In [43]:
B.cumsum(axis=1)

array([[2, 2],
       [3, 7]])

In [44]:
print(A.min())          # min value of all elements
print(A.max())          # max value of all elements

0
1


In [45]:
np.exp(B)        # exponential

array([[ 7.3890561 ,  1.        ],
       [20.08553692, 54.59815003]])

In [46]:
np.sqrt(B)       # squre root

array([[1.41421356, 0.        ],
       [1.73205081, 2.        ]])

In [47]:
A.argmin()       #position of min value of elements 

2

In [48]:
A.argmax()       #position of max value of elements

0

In [49]:
A[1,1]           #member of a array in (1,1) position

1